---
- name: Playbook setup jenkins server
  hosts: jenkins
  gather_facts: true
  tasks:
    - name: Download Jenkins repo file
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    
    - name: Import a key from a url
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Update system.
      ansible.builtin.yum:
        name: "*"
        state: latest
    
    - name: Install required dependencies for the jenkins package.
      ansible.builtin.yum:
        name:
          - fontconfig
          - java-17-openjdk
          - jenkins
        state: present

    - name: Start & enable jenkins service.    
      ansible.builtin.systemd_service:
        name: jenkins
        state: started
        enabled: true
        daemon-reload: true